spring:
  application:
    name: todo-list-app
    # 禁用 favicon
  # H2 資料庫配置
  datasource:
    url: jdbc:h2:mem:todoapp_new;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # H2 Console 配置
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
  
  # JPA 配置
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    defer-datasource-initialization: true
  
  # SQL 初始化配置
  sql:
    init:
      mode: never
      continue-on-error: false
  
  # Spring Session 配置
  session:
    store-type: jdbc
    timeout: 30m
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION
  
  # Thymeleaf 配置
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
  
  # Security 配置
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN
  mvc:
    favicon:
      enabled: false

# 日誌配置
logging:
  level:
    org.springframework.security: INFO
    org.springframework.session: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
    com.course: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# 伺服器配置
server:
  port: 8080
  servlet:
    context-path: /
    session:
      timeout: 30m
      cookie:
        max-age: 1800
        http-only: true
        secure: false

